name: CI


on:
  push:
    branches: [master, gha]


jobs:      
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [11.6.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        node-version: ${{ matrix.node }}
    - name: Setup Yarn
      run: npm install -g yarn@1.19.0
    - name: Download dependencies
      run: yarn run init
    - name: Build
      if: success()
      run: yarn run build:prod
